import { RxCrossCircled } from "react-icons/rx";
import styles from "../Input/Input.module.css";
import { BiPlusCircle } from "react-icons/bi";
import {
  type UseFormRegister,
  useFieldArray,
  type FieldArrayWithId,
  type Control,
  type FieldErrors,
} from "react-hook-form";
import type { MyFormValues } from "../../Enums/FormFields";
import RecipeDetails from "../RecipeDetails/RecipeDetails";
import { IoInformationCircle } from "react-icons/io5";
import { useState } from "react";
import {
  GenerateIngredientQuantity,
  GenerateTags,
} from "../../services/gemini";
import Skeleton from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";

export default function TagIngredientInputForm({
  header,
  register,
  control,
  name,
  error,
  getTitle,
  getServings,
}: {
  header: string;
  register: UseFormRegister<MyFormValues>;
  control: Control<MyFormValues>;
  name: "tag" | "ingredient";
  error: FieldErrors<MyFormValues>;
  getTitle?: () => string;
  getServings?: () => number;
}) {
  "use no memo";
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const { fields, append, remove, replace } = useFieldArray({ control, name });

  const title = getTitle?.() ?? "";
  const servings = getServings?.() ?? 0;
  const titleMissing = !title.trim();
  const servingsMissing = name === "ingredient" && !servings;

  const handleGenerate = async () => {
    const currentTitle = getTitle?.() ?? "";
    const currentServings = getServings?.() ?? 0;
    if (!currentTitle.trim()) return;

    setIsGenerating(true);
    setGenerateError(null);
    try {
      let items: { name: string }[] = [];
      if (name === "tag") {
        const result = await GenerateTags(currentTitle.trim());
        items = result?.tags ?? [];
      } else {
        if (!currentServings) {
          setIsGenerating(false);
          return;
        }
        const result = await GenerateIngredientQuantity(currentTitle, currentServings);
        items = result?.ingredients ?? [];
      }
      if (items.length === 0) {
        setGenerateError("No results returned — try again.");
      } else {
        replace(items);
      }
    } catch (err) {
      console.error(err);
      setGenerateError("Generation failed — please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const buttonLabel =
    name === "tag"
      ? isGenerating
        ? "Generating…"
        : "✦ Auto-tag my recipe"
      : isGenerating
        ? "Generating…"
        : `✦ Generate for ${servings > 0 ? servings : 0 } servings`;

  return (
    <div>
      <div style={{ marginBottom: "0.5rem" }}>
        <span className={styles.HeaderName}>{header}</span>
      </div>

      {isGenerating ? (
        <Skeleton
          count={name === "ingredient" ? 6 : 4}
          height={40}
          baseColor="#f0e6dc"
          highlightColor="#faf0e8"
          borderRadius="12px"
          style={{ marginBottom: "0.5rem" }}
        />
      ) : (
        <TagIngredientInputElement
          register={register}
          removeItem={remove}
          objectName={name}
          fields={fields}
          error={error}
        />
      )}

      <div className={styles.AutoGeneratedTags}>
        <AddButton
          text={header.toLowerCase()}
          onClick={() => append({ name: "" })}
        />
        <button
          type="button"
          className={styles.AddItemToRecipe}
          onClick={handleGenerate}
          disabled={isGenerating || titleMissing || servingsMissing}
          style={
            titleMissing || servingsMissing
              ? { opacity: 0.5, cursor: "not-allowed", backgroundColor: "#E8521A", color: "white" }
              : { backgroundColor: "#E8521A", color: "white" }
          }
        >
          {buttonLabel}
        </button>
      </div>
      {generateError && (
        <div style={{ fontSize: "0.72rem", color: "#c0392b", marginTop: "0.35rem" }}>
          ⚠ {generateError}
        </div>
      )}
    </div>
  );
}

export function TagIngredientInputElement({
  register,
  fields,
  objectName,
  removeItem,
  error,
}: {
  register: UseFormRegister<MyFormValues>;
  objectName: "tag" | "ingredient";
  removeItem: (index: number) => void;
  fields: FieldArrayWithId<MyFormValues, "tag" | "ingredient">[];
  error: FieldErrors<MyFormValues>;
}) {
  return (
    <div
      className={styles.InputWithButton}
      style={{ display: "flex", flexDirection: "column" }}
    >
      {fields.map((field, index) => (
        <div key={field.id}>
          <div
            style={{
              boxSizing: "border-box",
              display: "flex",
              marginBottom: "0.5rem",
              flexDirection: "row",
              gap: "0.7rem",
              alignItems: "center",
            }}
          >
            <input
              className={styles.input}
              defaultValue={field.name}
              placeholder={`Add ${objectName}`}
              {...register(`${objectName}.${index}.name` as const, {
                validate: {
                  valueNotNull: (value) =>
                    value !== "" || "This field cannot be null.",
                  duplicateValue: (value: string) =>
                    !fields.some(
                      (f, i) =>
                        i !== index &&
                        f.name.toLowerCase() === value.toLowerCase(),
                    ) || "Duplicate value not allowed",
                },
              })}
              style={{ width: "100%" }}
            />
            <RxCrossCircled
              size="1.4rem"
              onClick={() => {
                if (fields.length > 1) removeItem(index);
              }}
              style={{ cursor: "pointer", flexShrink: 0 }}
            />
          </div>
          <div className={styles.formError}>
            {error[objectName]?.[index] && (
              <RecipeDetails
                icon={IoInformationCircle}
                content={
                  error[objectName]?.[index]?.["name"]?.message as string
                }
                color="red"
                fontSize={0.8}
                size="1rem"
              />
            )}
          </div>
        </div>
      ))}
    </div>
  );
}

export function AddButton({
  onClick,
  text,
}: {
  onClick: () => void;
  text: string;
}) {
  return (
    <button className={styles.AddItemToRecipe} type="button" onClick={onClick}>
      <BiPlusCircle size="1.2rem" />
      <span>Add {text}</span>
    </button>
  );
}
